### PR TITLE
Editorial tweaks

### PR DESCRIPTION
**Pull request by cpu**
:wave: Not sure what the state of this ID submission is, but  I was fiddling with a draft [rustls-pemfile branch](https://github.com/rustls/pemfile/compare/main...cpu:pemfile:cpu-ech-pem) implementing this. Here are some drive-by tweaks to consider as output from that process :-) I recommend reviewing commit-wise.

### CODE REVIEW

**Comment by sftcd** [comment]
Hiya & thanks for the comments. This I-D is purely personal for now at least. I do think there's a win if multiple tools can use the same format though, so very happy to get/process comments and perhaps the right outcome might be an independent stream RFC. (There was some IMO unwise reluctance to accept such formats in the TLS WG, but they might see the light later:-)

I'll process the editorials etc. tomorrow here if that's ok.

**Comment by sftcd** [comment]
Turns out I forgot to push the -07 draft changes, sorry, and now I've done that it's not letting me merge this. Your changes look fine though, so is it easier for me to just make 'em in the master branch or if you can update the PR I can merge it then? (Sorry for lack of githubbery clue;-)

**Review by sftcd — APPROVED** [review]

**Review by sftcd — APPROVED** [review]

**Review by sftcd — APPROVED** [review]

**Review by sftcd — COMMENTED** [review]
was done for -07 anyway

**Comment by cpu** [comment]
I don't mind rebasing but I won't have a chance until tomorrow. If you want to handle it differently before then that's ok with me too.

**Comment by sftcd** [comment]
On 31/05/2024 23:01, Daniel McCarney wrote:
> I don't mind rebasing but I won't have a chance until tomorrow. If you want to handle it differently before then that's ok with me too.

There's no rush and good to record that there's been at least some
comment on the content (in case I wanna suggest adoption to the TLS
WG again:-)

S.

**Comment by cpu** [comment]
> I don't mind rebasing but I won't have a chance until tomorrow

Done :ballot_box_with_check:

**Comment by sftcd** [comment]
Thanks for those. Added an ack to you too (tell me if you'd prefer not).

**Pull request merged**
